-- Criação da Tabela
CREATE TABLE carros (
    id INT PRIMARY KEY AUTO_INCREMENT,
    continente VARCHAR(50),
    pais VARCHAR(50),
    marca VARCHAR(50),
    modelo VARCHAR(100),
    categoria VARCHAR(50)
);

-- Inserção de Dados - EUROPA
-- Alemanha
INSERT INTO carros (continente, pais, marca, modelo, categoria) VALUES
('EUROPA', 'ALEMANHA', 'Audi', 'A1', 'económico'),
('EUROPA', 'ALEMANHA', 'Audi', 'A3', 'económico'),
('EUROPA', 'ALEMANHA', 'Audi', 'A4', 'económico'),
('EUROPA', 'ALEMANHA', 'Audi', 'A5', 'média'),
('EUROPA', 'ALEMANHA', 'Audi', 'A6', 'média'),
('EUROPA', 'ALEMANHA', 'Audi', 'A7', 'média'),
('EUROPA', 'ALEMANHA', 'Audi', 'A8', 'luxo'),
('EUROPA', 'ALEMANHA', 'Audi', 'Q2', 'económico'),
('EUROPA', 'ALEMANHA', 'Audi', 'Q3', 'económico'),
('EUROPA', 'ALEMANHA', 'Audi', 'Q4 e-tron', 'económico'),
('EUROPA', 'ALEMANHA', 'Audi', 'Q5', 'média'),
('EUROPA', 'ALEMANHA', 'Audi', 'Q6 e-tron', 'média'),
('EUROPA', 'ALEMANHA', 'Audi', 'Q7', 'média'),
('EUROPA', 'ALEMANHA', 'Audi', 'Q8', 'luxo'),
('EUROPA', 'ALEMANHA', 'Audi', 'e-tron GT', 'luxo'),
('EUROPA', 'ALEMANHA', 'Audi', 'R8', 'luxo');

INSERT INTO carros (continente, pais, marca, modelo, categoria) VALUES
('EUROPA', 'ALEMANHA', 'BMW', 'Isetta', 'económico'),
('EUROPA', 'ALEMANHA', 'BMW', 'Série 1', 'económico'),
('EUROPA', 'ALEMANHA', 'BMW', 'Série 2', 'económico'),
('EUROPA', 'ALEMANHA', 'BMW', 'Série 3', 'média'),
('EUROPA', 'ALEMANHA', 'BMW', 'Série 4', 'média'),
('EUROPA', 'ALEMANHA', 'BMW', 'Série 5', 'média'),
('EUROPA', 'ALEMANHA', 'BMW', 'Série 7', 'luxo'),
('EUROPA', 'ALEMANHA', 'BMW', 'Série 8', 'luxo'),
('EUROPA', 'ALEMANHA', 'BMW', 'i4', 'média'),
('EUROPA', 'ALEMANHA', 'BMW', 'i5', 'média'),
('EUROPA', 'ALEMANHA', 'BMW', 'i7', 'luxo'),
('EUROPA', 'ALEMANHA', 'BMW', 'iX', 'luxo'),
('EUROPA', 'ALEMANHA', 'BMW', 'iX1', 'média'),
('EUROPA', 'ALEMANHA', 'BMW', 'iX2', 'média'),
('EUROPA', 'ALEMANHA', 'BMW', 'iX3', 'média'),
('EUROPA', 'ALEMANHA', 'BMW', 'X1', 'média'),
('EUROPA', 'ALEMANHA', 'BMW', 'X3', 'média'),
('EUROPA', 'ALEMANHA', 'BMW', 'X5', 'luxo'),
('EUROPA', 'ALEMANHA', 'BMW', 'XM', 'luxo'),
('EUROPA', 'ALEMANHA', 'BMW', 'Z4', 'média'),
('EUROPA', 'ALEMANHA', 'BMW', 'M2', 'média'),
('EUROPA', 'ALEMANHA', 'BMW', 'M3', 'luxo'),
('EUROPA', 'ALEMANHA', 'BMW', 'M4', 'luxo'),
('EUROPA', 'ALEMANHA', 'BMW', 'M5', 'luxo'),
('EUROPA', 'ALEMANHA', 'BMW', 'M8', 'luxo');

INSERT INTO carros (continente, pais, marca, modelo, categoria) VALUES
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'Classe A', 'económico'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'Classe B', 'económico'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'Classe C', 'média'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'Classe E', 'média'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'Classe S', 'luxo'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'Classe T', 'económico'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'Classe V', 'média'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'GLA', 'média'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'GLB', 'média'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'GLC', 'média'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'GLE', 'luxo'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'GLS', 'luxo'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'Classe G', 'luxo'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'EQA', 'média'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'EQB', 'média'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'EQC', 'luxo'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'EQE', 'luxo'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'EQS', 'luxo'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'EQT', 'económico'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'EQV', 'luxo'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'CLA', 'média'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'CLE', 'média'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'AMG GT', 'luxo'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'AMG SL', 'luxo'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'MayBach Classe S', 'luxo'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'MayBach EQS', 'luxo'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'MayBach GLS', 'luxo'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'MayBach SL', 'luxo'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'SLR McLaren', 'luxo');

INSERT INTO carros (continente, pais, marca, modelo, categoria) VALUES
('EUROPA', 'ALEMANHA', 'Volkswagen', 'Golf', 'económico'),
('EUROPA', 'ALEMANHA', 'Volkswagen', 'ID.3', 'económico'),
('EUROPA', 'ALEMANHA', 'Volkswagen', 'ID.4', 'média'),
('EUROPA', 'ALEMANHA', 'Volkswagen', 'ID.5', 'média'),
('EUROPA', 'ALEMANHA', 'Volkswagen', 'Tiguan', 'média'),
('EUROPA', 'ALEMANHA', 'Volkswagen', 'Passat', 'média'),
('EUROPA', 'ALEMANHA', 'Porsche', 'Taycan', 'luxo'),
('EUROPA', 'ALEMANHA', 'Porsche', 'Panamera', 'luxo'),
('EUROPA', 'ALEMANHA', 'Porsche', '911', 'luxo'),
('EUROPA', 'ALEMANHA', 'Porsche', '718', 'luxo'),
('EUROPA', 'ALEMANHA', 'Porsche', 'Cayenne', 'luxo'),
('EUROPA', 'ALEMANHA', 'Porsche', 'Macan', 'média'),
('EUROPA', 'ALEMANHA', 'Opel', 'Astra', 'económico'),
('EUROPA', 'ALEMANHA', 'Opel', 'Corsa', 'económico'),
('EUROPA', 'ALEMANHA', 'Opel', 'Mokka', 'económico'),
('EUROPA', 'ALEMANHA', 'Opel', 'Grandland', 'económico'),
('EUROPA', 'ALEMANHA', 'Smart', '#1', 'económico'),
('EUROPA', 'ALEMANHA', 'Smart', '#3', 'económico');

-- Itália
INSERT INTO carros (continente, pais, marca, modelo, categoria) VALUES
('EUROPA', 'ITALIA', 'Fiat', '500e', 'económico'),
('EUROPA', 'ITALIA', 'Fiat', 'Tipo', 'económico'),
('EUROPA', 'ITALIA', 'Fiat', '600e', 'económico'),
('EUROPA', 'ITALIA', 'Alfa Romeo', 'Tonale', 'média'),
('EUROPA', 'ITALIA', 'Alfa Romeo', 'Giulia', 'média'),
('EUROPA', 'ITALIA', 'Alfa Romeo', 'Stelvio', 'média'),
('EUROPA', 'ITALIA', 'Maserati', 'Grecale', 'luxo'),
('EUROPA', 'ITALIA', 'Maserati', 'Grancabrio', 'luxo'),
('EUROPA', 'ITALIA', 'Maserati', 'MCPura', 'luxo'),
('EUROPA', 'ITALIA', 'Maserati', 'MC20', 'luxo'),
('EUROPA', 'ITALIA', 'Maserati', 'GranTurismo', 'luxo'),
('EUROPA', 'ITALIA', 'Maserati', 'GT2', 'luxo'),
('EUROPA', 'ITALIA', 'Maserati', 'MCXtrema', 'luxo');

INSERT INTO carros (continente, pais, marca, modelo, categoria) VALUES
('EUROPA', 'ITALIA', 'Ferrari', 'Roma', 'luxo'),
('EUROPA', 'ITALIA', 'Ferrari', 'SF90', 'luxo'),
('EUROPA', 'ITALIA', 'Ferrari', 'Purosangue', 'luxo'),
('EUROPA', 'ITALIA', 'Ferrari', '296 GTB', 'luxo'),
('EUROPA', 'ITALIA', 'Ferrari', '12cilindri', 'luxo'),
('EUROPA', 'ITALIA', 'Ferrari', 'Daytona SP3', 'luxo'),
('EUROPA', 'ITALIA', 'Ferrari', 'Amalfi', 'luxo'),
('EUROPA', 'ITALIA', 'Ferrari', 'F12berlinetta', 'luxo'),
('EUROPA', 'ITALIA', 'Ferrari', '812', 'luxo'),
('EUROPA', 'ITALIA', 'Ferrari', 'GTC4Lusso', 'luxo'),
('EUROPA', 'ITALIA', 'Ferrari', 'California', 'luxo'),
('EUROPA', 'ITALIA', 'Ferrari', 'Portofino', 'luxo'),
('EUROPA', 'ITALIA', 'Ferrari', 'Testarossa', 'luxo'),
('EUROPA', 'ITALIA', 'Ferrari', '360', 'luxo'),
('EUROPA', 'ITALIA', 'Ferrari', '488', 'luxo'),
('EUROPA', 'ITALIA', 'Ferrari', 'F8', 'luxo'),
('EUROPA', 'ITALIA', 'Ferrari', 'Monza SP1', 'luxo'),
('EUROPA', 'ITALIA', 'Ferrari', 'Monza SP2', 'luxo'),
('EUROPA', 'ITALIA', 'Ferrari', '288 GTO', 'luxo'),
('EUROPA', 'ITALIA', 'Ferrari', 'F40', 'luxo'),
('EUROPA', 'ITALIA', 'Ferrari', 'F50', 'luxo'),
('EUROPA', 'ITALIA', 'Ferrari', 'Enzo', 'luxo'),
('EUROPA', 'ITALIA', 'Ferrari', 'LaFerrari', 'luxo'),
('EUROPA', 'ITALIA', 'Ferrari', 'F80', 'luxo');

INSERT INTO carros (continente, pais, marca, modelo, categoria) VALUES
('EUROPA', 'ITALIA', 'Lamborghini', 'Revuelto', 'luxo'),
('EUROPA', 'ITALIA', 'Lamborghini', 'Huracán', 'luxo'),
('EUROPA', 'ITALIA', 'Lamborghini', 'Urus', 'luxo'),
('EUROPA', 'ITALIA', 'Lamborghini', 'Aventador', 'luxo'),
('EUROPA', 'ITALIA', 'Lamborghini', 'Countach', 'luxo'),
('EUROPA', 'ITALIA', 'Lamborghini', 'Temerario', 'luxo'),
('EUROPA', 'ITALIA', 'Lamborghini', 'Miura', 'luxo'),
('EUROPA', 'ITALIA', 'Lamborghini', 'Diablo', 'luxo'),
('EUROPA', 'ITALIA', 'Lamborghini', 'Murciélago', 'luxo'),
('EUROPA', 'ITALIA', 'Lamborghini', 'Gallardo', 'luxo'),
('EUROPA', 'ITALIA', 'Pagani', 'Utopia', 'luxo'),
('EUROPA', 'ITALIA', 'Pagani', 'Huayra R', 'luxo'),
('EUROPA', 'ITALIA', 'Bugatti', 'Veyron', 'luxo'),
('EUROPA', 'ITALIA', 'Bugatti', 'Chiron', 'luxo'),
('EUROPA', 'ITALIA', 'Bugatti', 'Mistral', 'luxo'),
('EUROPA', 'ITALIA', 'Bugatti', 'Tourbillon', 'luxo');

-- França
INSERT INTO carros (continente, pais, marca, modelo, categoria) VALUES
('EUROPA', 'FRANÇA', 'Renault', 'Clio', 'económico'),
('EUROPA', 'FRANÇA', 'Renault', 'Captur', 'económico'),
('EUROPA', 'FRANÇA', 'Renault', 'Arkana', 'económico'),
('EUROPA', 'FRANÇA', 'Renault', 'Megane E-Tech', 'média'),
('EUROPA', 'FRANÇA', 'Renault', 'Austral', 'média'),
('EUROPA', 'FRANÇA', 'Peugeot', '208', 'económico'),
('EUROPA', 'FRANÇA', 'Peugeot', '2008', 'económico'),
('EUROPA', 'FRANÇA', 'Peugeot', '308', 'económico'),
('EUROPA', 'FRANÇA', 'Peugeot', '408', 'média'),
('EUROPA', 'FRANÇA', 'Peugeot', '3008', 'média'),
('EUROPA', 'FRANÇA', 'Citroën', 'C3', 'económico'),
('EUROPA', 'FRANÇA', 'Citroën', 'C4', 'económico'),
('EUROPA', 'FRANÇA', 'Citroën', 'ë-C4', 'económico'),
('EUROPA', 'FRANÇA', 'Citroën', 'C5 X', 'média'),
('EUROPA', 'FRANÇA', 'DS Automobiles', 'DS 3', 'média'),
('EUROPA', 'FRANÇA', 'DS Automobiles', 'DS 4', 'média'),
('EUROPA', 'FRANÇA', 'DS Automobiles', 'DS 7', 'média'),
('EUROPA', 'FRANÇA', 'DS Automobiles', 'DS 9', 'luxo');

-- Suécia
INSERT INTO carros (continente, pais, marca, modelo, categoria) VALUES
('EUROPA', 'SUÉCIA', 'Volvo', 'XC40', 'média'),
('EUROPA', 'SUÉCIA', 'Volvo', 'C40', 'média'),
('EUROPA', 'SUÉCIA', 'Volvo', 'EX30', 'económico'),
('EUROPA', 'SUÉCIA', 'Volvo', 'EX90', 'luxo'),
('EUROPA', 'SUÉCIA', 'Volvo', 'XC60', 'média'),
('EUROPA', 'SUÉCIA', 'Polestar', 'Polestar 2', 'média'),
('EUROPA', 'SUÉCIA', 'Polestar', 'Polestar 3', 'luxo'),
('EUROPA', 'SUÉCIA', 'Polestar', 'Polestar 4', 'média'),
('EUROPA', 'SUÉCIA', 'Koenigsegg', 'One:1', 'luxo'),
('EUROPA', 'SUÉCIA', 'Koenigsegg', 'Gemera', 'luxo'),
('EUROPA', 'SUÉCIA', 'Koenigsegg', 'Agera', 'luxo'),
('EUROPA', 'SUÉCIA', 'Koenigsegg', 'CC850', 'luxo');

-- Reino Unido
INSERT INTO carros (continente, pais, marca, modelo, categoria) VALUES
('EUROPA', 'REINO UNIDO', 'Jaguar', 'F-Type', 'luxo'),
('EUROPA', 'REINO UNIDO', 'Jaguar', 'F-Pace', 'luxo'),
('EUROPA', 'REINO UNIDO', 'Jaguar', 'E-Pace', 'média'),
('EUROPA', 'REINO UNIDO', 'Jaguar', 'I-Pace', 'luxo'),
('EUROPA', 'REINO UNIDO', 'Land Rover', 'Defender', 'luxo'),
('EUROPA', 'REINO UNIDO', 'Land Rover', 'Range Rover', 'luxo'),
('EUROPA', 'REINO UNIDO', 'Land Rover', 'Range Rover Sport', 'luxo'),
('EUROPA', 'REINO UNIDO', 'Land Rover', 'Evoque', 'média'),
('EUROPA', 'REINO UNIDO', 'Land Rover', 'Discovery Sport', 'média'),
('EUROPA', 'REINO UNIDO', 'Mini', 'Cooper', 'económico'),
('EUROPA', 'REINO UNIDO', 'Mini', 'Countryman', 'média'),
('EUROPA', 'REINO UNIDO', 'Mini', 'Electric', 'económico'),
('EUROPA', 'REINO UNIDO', 'Aston Martin', 'DB5', 'luxo'),
('EUROPA', 'REINO UNIDO', 'Aston Martin', 'DBX', 'luxo'),
('EUROPA', 'REINO UNIDO', 'Aston Martin', 'DB12', 'luxo'),
('EUROPA', 'REINO UNIDO', 'Aston Martin', 'Vantage', 'luxo'),
('EUROPA', 'REINO UNIDO', 'Aston Martin', 'Vanquish', 'luxo'),
('EUROPA', 'REINO UNIDO', 'Aston Martin', 'Valhalla', 'luxo'),
('EUROPA', 'REINO UNIDO', 'Aston Martin', 'Valkyrie', 'luxo');

INSERT INTO carros (continente, pais, marca, modelo, categoria) VALUES
('EUROPA', 'REINO UNIDO', 'McLaren', '765LT', 'luxo'),
('EUROPA', 'REINO UNIDO', 'McLaren', '720S', 'luxo'),
('EUROPA', 'REINO UNIDO', 'McLaren', 'Artura', 'luxo'),
('EUROPA', 'REINO UNIDO', 'McLaren', '750S', 'luxo'),
('EUROPA', 'REINO UNIDO', 'McLaren', 'GT', 'luxo'),
('EUROPA', 'REINO UNIDO', 'McLaren', '570S', 'luxo'),
('EUROPA', 'REINO UNIDO', 'McLaren', 'P1', 'luxo'),
('EUROPA', 'REINO UNIDO', 'McLaren', 'Senna', 'luxo'),
('EUROPA', 'REINO UNIDO', 'McLaren', 'Speedtail', 'luxo'),
('EUROPA', 'REINO UNIDO', 'McLaren', 'W1', 'luxo');

-- Outros Países Europeus
INSERT INTO carros (continente, pais, marca, modelo, categoria) VALUES
('EUROPA', 'ESPANHA', 'Seat', 'Leon', 'económico'),
('EUROPA', 'ESPANHA', 'Seat', 'Arona', 'económico'),
('EUROPA', 'ESPANHA', 'Seat', 'Ateca', 'económico'),
('EUROPA', 'ESPANHA', 'Cupra', 'Formentor', 'média'),
('EUROPA', 'ESPANHA', 'Cupra', 'Born', 'económico'),
('EUROPA', 'ESPANHA', 'Cupra', 'Tavascan', 'média'),
('EUROPA', 'CHECA', 'Skoda', 'Octavia', 'económico'),
('EUROPA', 'CHECA', 'Skoda', 'Fabia', 'económico'),
('EUROPA', 'CHECA', 'Skoda', 'Enyaq', 'média'),
('EUROPA', 'CHECA', 'Skoda', 'Kodiaq', 'média'),
('EUROPA', 'CHECA', 'Skoda', 'Superb', 'média'),
('EUROPA', 'ROMÉNIA', 'Dacia', 'Sandero', 'económico'),
('EUROPA', 'ROMÉNIA', 'Dacia', 'Logan', 'económico'),
('EUROPA', 'ROMÉNIA', 'Dacia', 'Spring', 'económico'),
('EUROPA', 'ROMÉNIA', 'Dacia', 'Duster', 'económico'),
('EUROPA', 'CROÁCIA', 'Rimac', 'Nevera', 'luxo');

-- AMÉRICA DO NORTE
INSERT INTO carros (continente, pais, marca, modelo, categoria) VALUES
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Ford', 'Focus', 'económico'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Ford', 'Fiesta', 'económico'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Ford', 'Puma', 'económico'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Ford', 'Kuga', 'média'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Ford', 'Mustang Mach-E', 'média'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Ford', 'Mustang GT', 'luxo'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Tesla', 'Model 3', 'média'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Tesla', 'Model Y', 'média'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Tesla', 'Model S', 'luxo'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Tesla', 'Model X', 'luxo'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Chevrolet', 'Camaro', 'média'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Chevrolet', 'Corvette C8 Stingray', 'luxo'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Chevrolet', 'Corvette C1', 'luxo'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Chevrolet', 'Corvette C7', 'luxo'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Jeep', 'Renegade', 'económico'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Jeep', 'Compass', 'média'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Jeep', 'Wrangler', 'média'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Jeep', 'Grand Cherokee', 'luxo'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Cadillac', 'Escalade', 'luxo');

-- ÁSIA
-- Japão
INSERT INTO carros (continente, pais, marca, modelo, categoria) VALUES
('ÁSIA', 'JAPÃO', 'Toyota', 'Supra MK4', 'média'),
('ÁSIA', 'JAPÃO', 'Toyota', 'Supra MK5', 'luxo'),
('ÁSIA', 'JAPÃO', 'Toyota', 'Corolla', 'económico'),
('ÁSIA', 'JAPÃO', 'Toyota', 'Yaris', 'económico'),
('ÁSIA', 'JAPÃO', 'Toyota', 'C-HR', 'média'),
('ÁSIA', 'JAPÃO', 'Toyota', 'RAV4', 'média'),
('ÁSIA', 'JAPÃO', 'Toyota', 'Aygo X', 'económico'),
('ÁSIA', 'JAPÃO', 'Toyota', 'bZ4X', 'média'),
('ÁSIA', 'JAPÃO', 'Lexus', 'LFA', 'luxo'),
('ÁSIA', 'JAPÃO', 'Lexus', 'UX', 'média'),
('ÁSIA', 'JAPÃO', 'Lexus', 'NX', 'média'),
('ÁSIA', 'JAPÃO', 'Lexus', 'RX', 'luxo'),
('ÁSIA', 'JAPÃO', 'Lexus', 'RZ', 'luxo'),
('ÁSIA', 'JAPÃO', 'Honda', 'Civic', 'económico'),
('ÁSIA', 'JAPÃO', 'Honda', 'Civic Type-R', 'média'),
('ÁSIA', 'JAPÃO', 'Honda', 'HR-V', 'económico'),
('ÁSIA', 'JAPÃO', 'Honda', 'CR-V', 'média'),
('ÁSIA', 'JAPÃO', 'Honda', 'Jazz', 'económico'),
('ÁSIA', 'JAPÃO', 'Honda', 'e:Ny1', 'média'),
('ÁSIA', 'JAPÃO', 'Mazda', 'Mazda 2', 'económico'),
('ÁSIA', 'JAPÃO', 'Mazda', 'Mazda 3', 'económico'),
('ÁSIA', 'JAPÃO', 'Mazda', 'CX-30', 'média'),
('ÁSIA', 'JAPÃO', 'Mazda', 'CX-5', 'média'),
('ÁSIA', 'JAPÃO', 'Mazda', 'MX-30', 'média'),
('ÁSIA', 'JAPÃO', 'Mazda', 'MX-5', 'média'),
('ÁSIA', 'JAPÃO', 'Mazda', 'MX-7', 'luxo'),
('ÁSIA', 'JAPÃO', 'Nissan', 'Qashqai', 'média'),
('ÁSIA', 'JAPÃO', 'Nissan', 'Juke', 'económico'),
('ÁSIA', 'JAPÃO', 'Nissan', 'X-Trail', 'média'),
('ÁSIA', 'JAPÃO', 'Nissan', 'Leaf', 'média'),
('ÁSIA', 'JAPÃO', 'Nissan', 'Ariya', 'luxo'),
('ÁSIA', 'JAPÃO', 'Subaru', 'Impreza', 'económico'), -- Corrigido de Imprenza
('ÁSIA', 'JAPÃO', 'Subaru', 'XV', 'média'),
('ÁSIA', 'JAPÃO', 'Subaru', 'Outback', 'média'),
('ÁSIA', 'JAPÃO', 'Subaru', 'Solterra', 'média'),
('ÁSIA', 'JAPÃO', 'Suzuki', 'Swift', 'económico'),
('ÁSIA', 'JAPÃO', 'Suzuki', 'Vitara', 'económico'),
('ÁSIA', 'JAPÃO', 'Suzuki', 'S-Cross', 'económico');

-- Coreia do Sul
INSERT INTO carros (continente, pais, marca, modelo, categoria) VALUES
('ÁSIA', 'COREIA DO SUL', 'Hyundai', 'i20', 'económico'),
('ÁSIA', 'COREIA DO SUL', 'Hyundai', 'i30', 'económico'),
('ÁSIA', 'COREIA DO SUL', 'Hyundai', 'Kona', 'média'),
('ÁSIA', 'COREIA DO SUL', 'Hyundai', 'Tucson', 'média'),
('ÁSIA', 'COREIA DO SUL', 'Hyundai', 'Ioniq 5', 'média'),
('ÁSIA', 'COREIA DO SUL', 'Hyundai', 'Ioniq 6', 'média'),
('ÁSIA', 'COREIA DO SUL', 'Kia', 'Ceed', 'económico'),
('ÁSIA', 'COREIA DO SUL', 'Kia', 'Sportage', 'média'),
('ÁSIA', 'COREIA DO SUL', 'Kia', 'Niro', 'média'),
('ÁSIA', 'COREIA DO SUL', 'Kia', 'EV6', 'média'),
('ÁSIA', 'COREIA DO SUL', 'Kia', 'EV9', 'luxo');

-- China
INSERT INTO carros (continente, pais, marca, modelo, categoria) VALUES
('ÁSIA', 'CHINA', 'MG', 'MG4', 'económico'),
('ÁSIA', 'CHINA', 'MG', 'MG5', 'económico'),
('ÁSIA', 'CHINA', 'MG', 'ZS EV', 'económico'),
('ÁSIA', 'CHINA', 'MG', 'Marvel R', 'média'),
('ÁSIA', 'CHINA', 'BYD', 'Atto 3', 'económico'),
('ÁSIA', 'CHINA', 'BYD', 'Dolphin', 'económico'),
('ÁSIA', 'CHINA', 'BYD', 'Seal', 'média'),
('ÁSIA', 'CHINA', 'BYD', 'Tang', 'luxo');
